openapi: 3.0.1

info:
  title: Peframe
  version: 0.0.1
  description: peframe is a open source tool to perform static analysis on malware and generic suspicious file. It can help malware researchers to detect packer, xor, digital signature, mutex, anti debug, anti virtual machine, suspicious sections and functions, macro and much more information about the suspicious files.

servers:
  - url: http://35.243.110.222/

tags:
  - name: Peframe
    description: Peframe API

paths:
  /:
    post:
      summary: embedding
      tags:
        - Peframe
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file1:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                format: binary
